/**
 * Visual Blocks Language
 *
 * Copyright 2012 Google Inc.
 * http://code.google.com/p/blockly/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generating Dart for text blocks.
 * @author fraser@google.com (Neil Fraser)
 * Due to the frequency of long strings, the 80-column wrap rule need not apply
 * to language files.
 * 
 * MODIFIED BY INDOBLOCKLY
 * Angga Maulana P 2012
 */

Blockly.C = Blockly.Generator.get('C');

Blockly.C.text = function() {
  // Text value.
  var code = Blockly.C.quote_(this.getTitleText('TEXT'));
  
  return [code, Blockly.C.ORDER_ATOMIC];
};

Blockly.C.text_join = function() {
  // Create a string made up of any number of elements of any type.
  
  
  if (this.itemCount_ == 0) {
    return ['\'\'', Blockly.C.ORDER_ATOMIC];
  } else if (this.itemCount_ == 1) {
    var argument0 = Blockly.C.valueToCode(this, 'ADD0', true) || '\'\'';
    return [argument0, Blockly.C.ORDER_UNARY_POSTFIX];
  } else if (this.itemCount_ == 2) {
    var argument0 = Blockly.C.valueToCode(this, 'ADD0') || '\'\'';
    var argument1 = Blockly.C.valueToCode(this, 'ADD1') || '\'\'';
       
           
    var code = argument0  + '#' + argument1;
    
     code = '//jointext ' + code;
    return [code, Blockly.C.ORDER_UNARY_POSTFIX];
  } else {
    var code = [];
    code[0] = (Blockly.C.valueToCode(this, 'ADD0', true) || '\'\'');
    for (var n = 1; n < this.itemCount_; n++) {
      code[n] = '#' + (Blockly.C.valueToCode(this, 'ADD' + n, true) || '\'\'');
    }
    code = code.join('');
   
    
    code = '//jointext '+code;
	return [code, Blockly.C.ORDER_UNARY_POSTFIX];
  }
};

Blockly.C.text_length = function() {
  // String length.
  var argument0 = Blockly.C.valueToCode(this, 'VALUE') || '\'\'';
  var tipe = Blockly.C.listTypeVar[argument0];
  if(tipe!=undefined){
     if(tipe=='int'){
         return ['sizeof(int)', Blockly.C.ORDER_UNARY_POSTFIX];
     } else if(tipe.match(/arrayint/g)){
         return ['sizeof('+argument0+')/sizeof(int)', Blockly.C.ORDER_UNARY_POSTFIX];
     } else if(tipe.match(/arraychar/g)){
         return ['sizeof('+argument0+')/sizeof(char)', Blockly.C.ORDER_UNARY_POSTFIX];
     } 
  }
  
  argument0 =  'strlen('+argument0 + ')';
  return [argument0, Blockly.C.ORDER_NONE];
};

Blockly.C.text_isEmpty = function() {
  // Is the string null?
  var argument0 = Blockly.C.valueToCode(this, 'VALUE') || '\'\'';
  Blockly.C.definitions_['isempty'] = 
     '\n//---FUNCTION GENERATED BY INDOBLOCKLY-----------\n'+
    'int isEmpty(char *teks){\n'+
    '  if(teks[0]==\'\\0\' || teks == NULL)\n'+
    '    return 1;\n'+
    '  else \n'+
    '    return 0;\n'+
    '}\n//-------------------------------------------\n\n';
  
  argument0 =   'isEmpty('+argument0+')';
  return [argument0 , Blockly.C.ORDER_UNARY_POSTFIX];
};

Blockly.C.text_endString = function() {
  // Return a leading or trailing substring.
  var first = this.getTitleValue('END') == 'FIRST';
  var code;
  if (first) {
    var argument0 = Blockly.C.valueToCode(this, 'NUM', true) || '1';
    var argument1 = Blockly.C.valueToCode(this, 'TEXT') || '\'\'';
    code =   'substring('+argument1+', 0,' + argument0 + ')';
  } else {
    var argument0 = Blockly.C.valueToCode(this, 'NUM') || '1';
    var argument1 = Blockly.C.valueToCode(this, 'TEXT', true) || '\'\'';
    code = 'substring(' + argument1 + ', strlen('+argument1+')-'+argument0+',' + argument0 + ')';
  }
  
  Blockly.C.definitions_['substring'] = 
      '\n//---FUNCTION GENERATED BY INDOBLOCKLY-----------\n'+
      'char hasilSubstring[maxChar];\n'+
      '//-inti dari skrip ini adalah membuat salinan variabel char namun awal alamat memori di tambah nilai int start\n'+
      'char *substring (char *teks,int start,int ambil){\n'+
      '    if(start+ambil>maxChar)\n'+
      '      printf("karakter yang diambil tidak mencukupi untuk disimpan di memori");\n'+
      '    else if(ambil>strlen(teks))\n'+
      '      printf("karakter yang diambil melebihi junlah karakter yang ada");\n'+
      '    else\n'+
       '     strncpy(hasilSubstring,teks+ambil,ambil);\n'+
       '   return hasilSubstring;\n'+
       '}\n//-------------------------------------------\n\n';
  return [code, Blockly.C.ORDER_UNARY_POSTFIX];
};

Blockly.C.text_indexOf = function() {
  // Search the text for a substring.
  var operator = this.getTitleValue('END') == 'FIRST' ? 'indexOf' : 'lastIndexOf';
  var argument0 = Blockly.C.valueToCode(this, 'FIND') || '\'\'';
  var argument1 = Blockly.C.valueToCode(this, 'VALUE') || '\'\'';
  var code = argument1 + '.' + operator + '(' + argument0 + ') + 1';
  
   return [code, Blockly.C.ORDER_UNARY_POSTFIX];
};

Blockly.C.text_charAt = function() {
  // Get letter at index.
  var argument0 = Blockly.C.valueToCode(this, 'AT', true) || '1';
  var argument1 = Blockly.C.valueToCode(this, 'VALUE') || '[]';
  // Blockly uses one-based arrays.
  if (argument0.match(/^\d+$/)) {
    // If the index is a naked number, decrement it right now.
    argument0 = parseInt(argument0, 10) - 1;
    if(argument0==-1){
        argument0=0;
    }
  } else {
    // If the index is dynamic, decrement it in code.
    argument0 += ' - 1';
  }
  var code = argument1 + '[' + argument0 + ']';
  return [code, Blockly.C.ORDER_UNARY_POSTFIX];
};

Blockly.C.text_changeCase = function() {
  // Change capitalization.
  var mode = this.getTitleValue('CASE');
  var operator = Blockly.C.text_changeCase.OPERATORS[mode];
  var code;
  if (operator) {
    // Upper and lower case are functions built into Dart.
    var argument0 = Blockly.C.valueToCode(this, 'TEXT') || '\'\'';
    code = operator + argument0 +')' ;
  } else {
     
    if (!Blockly.C.definitions_['toTitleCase']) {
      // Title case is not a native Dart function.  Define one.
      var functionName = Blockly.C.variableDB_.getDistinctName('text_toTitleCase',
          Blockly.Generator.NAME_TYPE);
      Blockly.C.text_changeCase.toTitleCase = functionName;
      var func = [];
      func.push('char * ' + functionName + '(char * kata) {');     
      func.push('    static char kata_buf[maxChar];\n   strncpy(kata_buf,kata,maxChar);\n    kata_buf[0] = toupper(kata_buf[0]);\n    return kata_buf;');
      func.push('}');
      Blockly.C.definitions_['toTitleCase'] = func.join('\n');
    }
    var argument0 = Blockly.C.valueToCode(this, 'TEXT', true) || '\'\'';
    code = Blockly.C.text_changeCase.toTitleCase + '(' + argument0 + ')';
  }
  return [code, Blockly.C.ORDER_UNARY_POSTFIX];
};

Blockly.C.text_changeCase.OPERATORS = {
  UPPERCASE: 'strupr(',
  LOWERCASE: 'strlwr(',
  TITLECASE: null
};

Blockly.C.text_trim = function() {
  // Trim spaces.
  var mode = this.getTitleValue('MODE');
  var operator = Blockly.C.text_trim.OPERATORS[mode];
  var argument0 = Blockly.C.valueToCode(this, 'TEXT') || '\'\'';
  Blockly.C.definitions_['trim'] = 
      '\n//---FUNCTION GENERATED BY INDOBLOCKLY-----------------\n'+
       '//---fungsi ini hanya menghilangkan satu spasi saja di depan atau belakang-----------------\n\n'+
      'char hasilTrim[maxChar];\n\nchar *trim(char * teks, char *tipe){\n'+
   '  if(strcmp(teks,"both")){\n'+
    '   if(isspace(teks[0])!=0 && isspace(teks[strlen(teks)-1])!=0){\n'+
    '       strncpy(hasilTrim,teks,maxChar);\n'+
    '        int i=1,j=0;\n'+
    '        for(i=1;i&lt;strlen(teks);i++){\n'+
    '           if(teks[i]!=\'\\0\'){\n'+
    '               hasilTrim[j] = teks[i];\n'+
    '                j++;\n'+
    '            }\n'+
    '        }\n'+
    '        hasilTrim[j-1] = \'\\0\';\n'+
    '        return hasilTrim;\n'+
    '    }'+
     '    else{\n'+    
        '        return teks;\n'+
    '     }\n'+
   '  }else if(strcmp(teks,"left")){\n'+
    '  if(isspace(teks[0])!=0){\n'+
     '      strncpy(hasilTrim,teks,maxChar);\n'+
     '       int i=1,j=0;\n'+
     '       for(i=1;i&lt;strlen(teks);i++){\n'+
     '           if(teks[i]!=\'\\0\'){\n'+
     '               hasilTrim[j] = teks[i];\n'+
    '                j++;\n'+
    '            }\n'+
    '        }\n'+
    '        return hasilTrim;\n'+
    '    }'+
     '     else{\n'+    
        '        return teks;\n'+
    '     }\n'+
   ' }else if(strcmp(teks,"right")){\n'+
   '  if(isspace(teks[strlen(teks)])!=0){\n'+
     '   strncpy(hasilTrim,teks,maxChar);\n'+
     '   hasilTrim[strlen(hasilTrim)-1] = \'\\0\';\n'+
    '    return hasilTrim;\n'+
    '     }else{\n'+    
        '        return teks;\n'+
    '    }'+
    ' } else{\n'+    
        '        return teks;\n'+
    '  }\n'+
'}\n'+
'//---------------------------------------------------------------\n\n'
;
  argument0 = 'trim('+argument0 +',"'+ operator+'")';
  return [argument0, Blockly.C.ORDER_UNARY_POSTFIX];
};

Blockly.C.text_trim.OPERATORS = {
  LEFT: 'left',
  RIGHT: 'right',
  BOTH: 'both'
};

Blockly.C.text_print = function() {
  // Print statement.
  var format = '';
  var argument0 = Blockly.C.valueToCode(this, 'TEXT', true) || '\'\'';
      argument0 = argument0.replace(/^\(/g,'');
      argument0 = argument0.replace(/\)$/g,'');      
      argument0 = argument0.replace(/^\/\/jointext\s/g,'');  
    
      var newArg = argument0.split('#');
        var cekString = /^"+[\w]*"/g;
        var cekFungsiReturnChar = /^(strlwr\(|strupr\(|substring\(|trim\(|strcat\(|text_toTitleCase\()[\w\W]*/g;
        var cekFungsiReturnFloat = /^(sqrt\(|floor\(|ceil\(|sin\(|cos\(|tan\(|asin\(|acos\(|atan\(|log\(|log10\(|exp\(|pow\()[\w\W]*/g;     
        var cekAngkaFloat = /(\d\.\d|\d\.\s\d)/g;
        var cekAngkaInt = /(^-\d+$|^\d+$|((\d\s\+\s\d)+|(\d\s\-\s\d)+|(\d\s\*\s\d)+|(\d\s\/\s\d)+))/g;
        var cekVariabel = /^[a-zA-Z_]+[\w]?/g;

      
      for(var i=0;i<newArg.length;i++){
           
          if(newArg[i]=='"\\\\n"'){
              //berupa enter
              
              format += '%s\\n';
              argument0 = argument0.replace(/\\\\n/g,'');
              
          }else if(newArg[i]=='\'\''){
              //berupa enter
              
              format += '%s ';
              argument0 = argument0.replace(/\'\'/g,'""');
              
          }else if(newArg[i].match(cekFungsiReturnFloat)){
              //berupa fungsi return float
              format += '%.2f ';
                            
          }else if(newArg[i].match(cekFungsiReturnChar)){
              //fungsi2 penghasil string strupr,strlwr,
             
              format += '%s ';
          }else if(newArg[i].match(cekAngkaInt)){
              //berupa angka
              
              format += "%d ";
          }else if(newArg[i].match(cekAngkaFloat)){
              //berupa angka
              
              format += "%d ";
          }else if(newArg[i].match(cekString)){
              //string murni
            
              format += '%s ';
          }else if(newArg[i].match(/^[a-zA-Z_]+\[[\w\W\s]*\]$/g)){
              //berupa index suatu array
              //tentukan array jenis apa
              
              var ambilVar = newArg[i].replace(/\[[\w\W\s]*\]/g,'');
              if(Blockly.C.listTypeVar[ambilVar]!=undefined){
                  if(Blockly.C.listTypeVar[ambilVar].match(/arrayint/g)){
                      format += '%d ';
                  }if(Blockly.C.listTypeVar[ambilVar].match(/arraychar/g)){
                      format += '%s ';
                  }
              }
          }else if(newArg[i].match(cekVariabel)){
              //berupa variabel
              
              if(Blockly.C.listTypeVar[newArg[i]]!=undefined){
                  
                  if(Blockly.C.listTypeVar[newArg[i]]=='char'){
                      format += '%s ';
                  }else if(Blockly.C.listTypeVar[newArg[i]]=='int'){
                      format += '%d ';
                  }else if(Blockly.C.listTypeVar[newArg[i]]=='float'){
                      format += '%f ';
                  }else if(Blockly.C.listTypeVar[newArg[i]].match(/arrayint/g)){
                        format += '%d ';
                  } else if(Blockly.C.listTypeVar[newArg[i]].match(/arraychar/g)){
                        format += '%s ';
                  }else{
                      format += '%d ';
                  }
              }else{
                  
                  format +='%u ';
              }
          }else{
              
              format += '%u ';
          }
      }
 
  
  return 'printf("'+format+' ",' + newArg.join(',') + ');\n';
};

Blockly.C.text_prompt = function() {
  // Prompt function.
  //Blockly.C.definitions_['import_dart_html'] = '#import(\'dart:html\');';
  var msg = Blockly.C.quote_(this.getTitleValue('TEXT'));  
  var toNumber = this.getTitleValue('TYPE') == 'NUMBER';
  var code = '';
  if (toNumber) {
       code = '//input variabel Angka\nprintf(' + msg + ');scanf(';
	 
      
  }else{
     code =  '//input variabel String\nprintf(' + msg + ');gets(';
	
  }
  return [code, Blockly.C.ORDER_UNARY_POSTFIX];
  
};

